<a href="https://colab.research.google.com/github/brunofariasdeo/data-science/blob/main/labs/Laborat%C3%B3rio_9_Eng_de_Dados_CIn_UFPE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Assunto do Laboratório 9:
- Uso de vetores e matrizes da biblioteca NUMPY.

### Questão 1:

Construa um programa que preenche um vetor de inteiros de 100 números, colocando 0 nas posições pares e 1 nas ímpares.


In [3]:
import numpy as np

def oddAndEven():
  a = np.full((10,10),2)

  a[::2,:] = 0
  a[1::2,:] = 1
  a[:,::2] = 0
  a[:,1::2] = 1

  return a

print(oddAndEven())


[[0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]]


### Questão 2:

Construa um programa que lê, soma e imprime o resultado da soma de um vetor de inteiros de 10 posições.


In [ ]:
def sumArray(array):
  return array.sum()

print(sumArray(np.full((2,5),5)))

50


### Questão 3:

Construa um programa que multiplique os valores de um vetor de reais de 20 posições pelos valores de um outro vetor de reais de 20 posições. O primeiro vetor deve ser inicializado com valores crescentes a partir de 1 e o segundo vetor com valores decrescentes a partir de 20. Os resultados das multiplicações devem ser armazenados num terceiro vetor.


In [ ]:
def multiplyArrays(ascendingArray, descendingArray):
  return ascending*descending

ascending = np.arange(20).reshape(4, 5)
ascending += 1

descending = np.arange(20).reshape(4, 5)
descending += 1
descending = np.flip(descending)

print(multiplyArrays(ascending, descending))

[[ 20  38  54  68  80]
 [ 90  98 104 108 110]
 [110 108 104  98  90]
 [ 80  68  54  38  20]]


### Questão 4:

Leia um vetor de 16 posições e troque os 8 primeiros valores pelos 8 últimos e vice-versa. Escreva ao final o vetor obtido.


In [ ]:
def switchArray(array):
  firstEightValues = sixteen[0:2, :]
  lastEightValues = sixteen[2:4, :]

  return np.concatenate((lastEightValues, firstEightValues), axis=0)

print(switchArray(np.arange(16).reshape(4, 4)))

[[ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]]


### Questão 5

Refaça as questões anteriores criando uma função para cada uma delas.

In [ ]:
##codigo vai aqui


### Questão 6:

Construa um algoritmo que efetue e apresente o resultado da soma entre duas matrizes 3 x 5. Inicialize a matriz com valores quaisquer e imprima o resultado na tela.


In [ ]:
def sumMatrices(firstArray, secondArray):
  return firstArray + secondArray

a = np.full((3,5),2)
b = np.full((3,5),3)

print(sumMatrices(a,b))


[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


### Questão 7:
Faça um programa que multiplica uma matriz 3 x 3 de inteiros por um escalar k e imprima o resultado na tela. O usuário deve fornecer os valores da matriz e de k.


In [ ]:
def multiplyArrayByConstant(k, array):
  return k * array

c = np.full((3,3),2)
k = 5

print(multiplyArrayByConstant(k,c))

[[10 10 10]
 [10 10 10]
 [10 10 10]]


### Questão 8:
Leia uma matriz 20 x 20. Leia também um valor X. O programa deverá fazer uma busca desse valor na matriz e, ao final escrever a localização (linha e coluna) ou uma mensagem de “não encontrado”.


In [ ]:
def findValueInArray(x, array):
  if x in c:
    result = np.where(c==x)
    return result
  else:
    return('Not found')

x = 1

c = np.reshape(np.arange(0,400),(20,20))

print(findValueInArray(x,c))

(array([0]), array([1]))


### Questão 9:

Dada uma matriz 5x5, elabore um algoritmo que imprima:

- A diagonal principal

- A diagonal secundária

- A soma da linha 4
- A soma da coluna 2

- Tudo, exceto a diagonal principal


In [ ]:
print('\n Array \n')
d = np.reshape(np.arange(0,25),(5,5))
print(d)

print('\n Diagonal Principal \n')
np.diag(d, 0)

dFlipped = np.fliplr(d)
print(dFlipped)

print('\n Diagonal Secundária \n')
print(np.diag(dFlipped,0))

print('\n Soma da linha 4 \n')
print(d[4,:].sum())

print('\n Soma da coluna 2 \n')
print(d[:,2].sum())

print('\n Somar tudo menos a diagonal principal \n')
print(d[:,:].sum() - np.diag(d,0).sum())


 Array 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

 Diagonal Principal 

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]
 [24 23 22 21 20]]

 Diagonal Secundária 

[ 4  8 12 16 20]

 Soma da linha 4 

110

 Soma da coluna 2 

60

 Somar tudo menos a diagonal principal 

240


### Questão 10:

Faça um programa para multiplicar duas matrizes com tamanho até 10x10, armazenando o resultado em uma terceira matriz. 

- O programa deve solicitar ao usuário as duas dimensões das duas matrizes;

- O programa deve verificar se as matrizes podem ser multiplicadas e apresentar uma mensagem de erro, caso não seja possível.


In [4]:
def multiplyArraysWithMaximumSize(firstMatrix, secondMatrix):
  firstMatrixRows = int(input('First matrix number of rows: '))
  firstMatrixColumns = int(input('First matrix number of columns: '))

  secondMatrixRows = int(input('Second matrix number of rows: '))
  secondMatrixColumns = int(input('Second matrix number of columns: '))

  if(firstMatrixColumns != secondMatrixRows | (firstMatrixRows | firstMatrixColumns | secondMatrixRows | secondMatrixColumns > 10)):
    return 'This operation is not possible'
  else:
    return np.mat(firstMatrix) * np.mat(secondMatrix)

dale = np.full((2,5),5)
beleza = np.full((5,2),6)

print(multiplyArraysWithMaximumSize(dale,beleza))

First matrix number of rows: 2
First matrix number of columns: 5
Second matrix number of rows: 5
Second matrix number of columns: 2
[[150 150]
 [150 150]]


### Questão 11:
Refaça o programa anterior transformando apenas o código que faz a multiplicação das matrizes em uma função. 
- A função recebe como parâmetro as três matrizes e as dimensões das duas primeiras matrizes.  O resultado da multiplicação das duas primeiras matrizes deve ser armazenado na terceira matriz.;

- A função deve retornar falso se não for possível multiplicar as matrizes, e verdadeiro caso contrário.

- A função não deve ler as matrizes, imprimir o resultado, nem a mensagem de erro. Isto deve ser feito na função principal.


In [ ]:
## o codigo vai aqui