#### Fundamentals

In [1]:
import numpy as np


In [26]:
a = np.array([1,2,3], dtype='int16')
a

array([1, 2, 3], dtype=int16)

In [10]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [18]:
# Get dimension
a.ndim, b.ndim

(1, 2)

In [21]:
# Get Shape
a.shape, b.shape

((3,), (2, 3))

In [27]:
# Get Type
a.dtype, b.dtype

(dtype('int16'), dtype('float64'))

In [29]:
# Get Size
a.itemsize, b.itemsize

(2, 8)

In [30]:
#Get Total Size
a.size

3

#### Accessing/changing specific elements, rows, columns, etc

In [33]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [39]:
# Get a specific element [r,c]
c[0,5], c[1,5], c[1,-2]

(6, 13, 13)

In [42]:
# Get a specific row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [43]:
# Get a specific column
c[:, 2]

array([ 3, 10])

In [48]:
# Getting a little more fancy (startIndex : endIndex : stepSize)
c[0, 1:6:1], c[0, 1:6:2], c[0, 1:6:3]

(array([2, 3, 4, 5, 6]), array([2, 4, 6]), array([2, 5]))

In [52]:
c[1,5] = 20
print(c)

c[:,2] = [1,2]
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [81]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [56]:
# Get specific element (work outside in)
d[0,1,1], d[:, 1,:]

(4,
 array([[3, 4],
        [7, 8]]))

In [83]:
# Replace 
d[:,0,:] = [[9,9],[8,8]]
print(d)

[[[9 9]
  [3 4]]

 [[8 8]
  [7 8]]]


#### Initializing different types of array

In [86]:
# All 0s matrix
print(np.zeros(5))
print(np.zeros((2,3)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [90]:
# All 1s matrix
np.ones((4,2,2))
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [89]:
# Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [94]:
# Any other number (full_like)
print(c)

print(np.full_like(c, 4))

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [97]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.97039001, 0.88480523],
       [0.29987422, 0.14602017],
       [0.88338944, 0.68278242],
       [0.8224529 , 0.15061284]])

In [98]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 0,  1, -1],
       [ 4,  1,  0],
       [-1,  6,  5]])

In [101]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [103]:
# Repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [105]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Copying Arrays

In [108]:
a = np.array([1,2,3])
b=a
b[0]=100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [109]:
a = np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


#### Mathematics

In [122]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [124]:
a + 2

array([3, 4, 5, 6])

In [113]:
a - 2

array([-1,  0,  1,  2])

In [114]:
a * 2

array([2, 4, 6, 8])

In [115]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [125]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [126]:
a ** 2

array([ 1,  4,  9, 16])

In [128]:
# Take the sin
np.sin(a), np.cos(a)

(array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ]),
 array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362]))