#### Construa um algoritmo que efetue e apresente o resultado da soma entre duas matrizes 3 x 5. Inicialize a matriz com valores quaisquer e imprima o resultado na tela.

In [2]:
import numpy as np

In [7]:
a = np.full((3,5),2)
print(a)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [8]:
b = np.full((3,5),3)
print(b)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [9]:
a + b

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

#### Faça um programa que multiplica uma matriz 3 x 3 de inteiros por um escalar k e imprima o resultado na tela. O usuário deve fornecer os valores da matriz e de k.

In [14]:
k = int(input())

 3


In [17]:
b = np.full((3,3),5)
print(b)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [18]:
k * b

array([[15, 15, 15],
       [15, 15, 15],
       [15, 15, 15]])

#### Leia uma matriz 20x20. Leia também um valor X. O programa deverá fazer uma busca desse valor na matriz e, ao final escrever a localização (linha e coluna) ou uma mensagem de “não encontrado”.

In [47]:
x = 1

c = np.reshape(np.arange(0,400),(20,20))

if x in c:
    result = np.where(c==x)
    print(result)
else:
    print('Not found')

(array([0]), array([1]))


In [48]:
x = -1

c = np.reshape(np.arange(0,400),(20,20))

if x in c:
    result = np.where(c==x)
    print(result)
else:
    print('Not found')

Not found


#### Dada uma matriz 5x5, elabore um algoritmo que imprima:
○ A diagonal principal
○ A diagonal secundária
○ A soma da linha 4
○ A soma da coluna 2
○ Tudo, exceto a diagonal principal

In [56]:
d = np.reshape(np.arange(0,25),(5,5))
print(d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [57]:
print('Diagonal Principal')
np.diag(d, 0)

Diagonal Principal


array([ 0,  6, 12, 18, 24])

In [65]:
dFlipped = np.fliplr(d)
print(dFlipped)

print('Diagonal Secundária')
print(np.diag(dFlipped,0))

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]
 [24 23 22 21 20]]
Diagonal Secundária
[ 4  8 12 16 20]


In [70]:
print('Soma da linha 4')
d[4,:].sum()

Soma da linha 4


110

In [71]:
print('Soma da coluna 2')
d[:,2].sum()

Soma da coluna 2


60

In [77]:
print('Somar tudo menos a diagonal principal')
d[:,:].sum() - np.diag(d,0).sum()

Somar tudo menos a diagonal principal


240